package com.tanran.model.media.pojos;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ad_sensitive
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AdSensitive implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 敏感词
     */
    private String sensitives;

    /**
     * 创建时间
     */
    private Date createdTime;
}