package com.tanran.model.user.pojos;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.tanran.model.annotation.IdEncrypt;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ap_user_follow
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ApUserFollow  {
    /**
     * 主键
     */
    private Long id;

    /**
     * 用户ID
     */
    @IdEncrypt
    private Long userId;

    /**
     * 粉丝ID
     */
    @IdEncrypt
    private Integer followId;

    /**
     * 粉丝昵称
     */
    private String followName;

    /**
     * 关注度
            0 偶尔感兴趣
            1 一般
            2 经常
            3 高度
     */
    private short level;

    /**
     * 是否动态通知
     */
    private Boolean isNotice;

    /**
     * 创建时间
     */
    private Date createdTime;

}